# Generated by Django 5.2 on 2025-05-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
