# Generated by Django 5.2 on 2025-05-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон'),
        ),
    ]
