# Generated by Django 5.2 on 2025-05-08 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(max_length=500, verbose_name='Описание задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дата регистрации')),
                ('comments', models.TextField(max_length=500, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('Открыто', 'Открыто'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено')], default='Открыто', max_length=9, verbose_name='Статус')),
                ('executor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
